FROM oven/bun:1

# Install OpenSSL and dependencies for Prisma
RUN apt-get update -y && apt-get install -y openssl libssl-dev

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/backend ./apps/backend

# Install dependencies
RUN bun install

# Generate Prisma client
RUN bun run db:generate

EXPOSE 8080

# Start backend
CMD ["bun", "run", "start:backend"]
